import './db/academy-db';
import './db/report-db';
import './db/overall-dashboard-db';
import './db/teacher-report-db';
import './db/institute-report-db';
import './db/auth-db';
import './db/calendar-db';
import './db/chat-db';
import './db/contacts-db';
import './db/e-commerce-db';
import './db/faq-db';
import './db/file-manager-db';
import './db/icons-db';
import './db/invoices-db';
import './db/knowledge-base-db';
import './db/mail-db';
import './db/notes-db';
import './db/bookmark-db';
import './db/profile-db';
import './db/subject-dashboard-db';
import './db/quick-panel-db';
import './db/scrumboard-db';
import './db/search-db';
import './db/todo-db';
import './db/notification-panel-db';
import mock from './mock';

mock.onAny().passThrough();
